### ISSUE TITLE
no infromation on how to execute it

### ISSUE THREAD

**Issue by harshith8854** [Abhiram2001/Blockhain-Criminal-Database#1]
adding more information about the execution would help me to get through your project and learn from it:)

**Comment by Abhiram2001** [comment]
It is built using truffle and ganache 

D-App Part:
- Install Node JS, Truffle
- Install Ganache
- Create Meta Mask Account and connect it with your local Ganache local block chain
- And Use truffle commands for local deploy

** Need Backend code(GCP Platform Integration) if require Contact Me

Refer here for More Information :

- https://trufflesuite.com/index.html
